services:
  backend:
    build: 
      context: ./
    container_name: postnote_backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DATABASE_URL : postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: postgres_container
    restart : always
    environment:
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB : ${DB_NAME}
      
    ports:
      - "${LOCAL_DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes: 
  postgres_data:
    
      

        
